import java.util.regex.Matcher
import se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask
import static org.apache.commons.lang3.StringUtils.repeat

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version "$mod_dev_gradle"
    id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin' version '3.1.1'
    id 'me.modmuss50.mod-publish-plugin' version '1.1.0'
    id 'com.diffplug.spotless' version '8.0.0'
}

def isRelease = System.getenv('CURSEFORGE_TOKEN')
if (!isRelease) {
    mod_version += '-snapshot'
}

version = "$minecraft_version-$mod_version"

group = 'mods.railcraft'
base {
    archivesName = 'railcraft-reborn'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
        if (System.getProperty('idea.active')) {
            vendor = JvmVendorSpec.JETBRAINS
        }
    }
}

println(repeat('*', 60))
println("Project Version: $version")
println("Java: ${System.getProperty('java.version')}")
println("JVM: ${System.getProperty('java.vm.version')} (${System.getProperty('java.vendor')})")
println("Arch: ${System.getProperty('os.arch')}")
println(repeat('*', 60))

sourceSets {
    api {
        // API has no resources
        resources.srcDirs = []
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
    main {
        compileClasspath += api.output
        runtimeClasspath += api.output
        resources {
            srcDir 'src/generated/resources'
            exclude '.cache'
        }
    }
    test {
        compileClasspath += api.output
        runtimeClasspath += api.output
    }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    validateAccessTransformers = true

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG

            systemProperty 'neoforge.enabledGameTestNamespaces', 'railcraft'

            if (System.getProperty('idea.active')) {
                jvmArguments.add("-XX:+AllowEnhancedClassRedefinition")
            }
        }

        client {
            client()
            gameDirectory = project.file('runs/client')
        }

        server {
            server()
            gameDirectory = project.file('runs/server')
            programArgument '--nogui'
        }

        data {
            data()
            gameDirectory = project.file('runs/data')
            programArguments.addAll '--mod', 'railcraft', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        gameTestServer {
            type = "gameTestServer"
            gameDirectory = project.file('runs/gameTestServer')
        }
    }

    mods {
        'railcraft' {
            sourceSet sourceSets.api
            sourceSet sourceSets.main
            sourceSet sourceSets.test
        }
    }

    unitTest {
        enable()
        testedMod = mods.railcraft
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    maven {
        name = 'JEI/Patchouli'
        url = 'https://maven.blamejared.com/'
    }
    maven {
        name = 'curseforge'
        url = 'https://www.cursemaven.com'
    }
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
}

dependencies {
    testImplementation platform("org.junit:junit-bom:$jupiter_version")
    testImplementation 'org.junit.jupiter:junit-jupiter'

    compileOnly "mezz.jei:jei-$minecraft_version-common-api:$jei_version"
    compileOnly "mezz.jei:jei-$minecraft_version-neoforge-api:$jei_version"
    localRuntime "mezz.jei:jei-$minecraft_version-neoforge:$jei_version"

    compileOnly "dev.emi:emi-neoforge:$emi_version+$minecraft_version:api"
    //localRuntime "dev.emi:emi-neoforge:$emi_version+$minecraft_version"

    compileOnly "vazkii.patchouli:Patchouli:$patchouli_version:api"
    localRuntime "vazkii.patchouli:Patchouli:$patchouli_version"

    implementation "curse.maven:jade-api-324717:$jade_id"
    implementation "curse.maven:dynamiclights-reforged-551736:$dynamiclights_id"

    localRuntime "curse.maven:mekanism-268560:6895130"//mekanism
    localRuntime "curse.maven:mekanism-268567:6895134"//mekanism-tools
    //localRuntime "curse.maven:sodium-394468:6173749"
    //localRuntime "curse.maven:sodium-options-api-1103431:6100815"
    //localRuntime "curse.maven:reeses-sodium-options-511319:6091021"
}

test {
    useJUnitPlatform()
}

spotless {
  java {
    target 'src/*/java/**/*.java'
    importOrder('\\#', 'java|javax|org|com|')

    endWithNewline()
    trimTrailingWhitespace()
    removeUnusedImports()
    leadingTabsToSpaces(2)
    custom 'noWildcardImports', { String fileContents ->
        if (fileContents.contains('*;\n')) {
            throw new InvalidUserDataException('No wildcard imports are allowed!')
        }
        fileContents
    }
    bumpThisNumberIfACustomStepChanges(1)
  }
}

tasks.register('generatePackageInfos') {
  def srcDirs = [
    layout.projectDirectory.dir("src/main/java"),
    layout.projectDirectory.dir("src/api/java")
  ]
  def javaFiles = files(srcDirs.collect { dir ->
    project.fileTree(dir) { include '**/*.java' }
  })

  srcDirs.each { inputs.dir(it) }
  outputs.upToDateWhen { false }

  doLast {
    javaFiles.each { javaFile ->
      def packageInfoFile = new File(javaFile.parent, 'package-info.java')
      if (!packageInfoFile.exists()) {
        def pkgName = javaFile.toString().replaceAll(Matcher.quoteReplacement(File.separator), '/')
        pkgName = pkgName.substring(pkgName.indexOf('mods/railcraft/'), pkgName.lastIndexOf('/'))
        pkgName = pkgName.replaceAll('/', '.')

        def pkgInfoText = """
            |@FieldsAreNonnullByDefault
            |@MethodsReturnNonnullByDefault
            |@ParametersAreNonnullByDefault
            |package $pkgName;
            |
            |import javax.annotation.ParametersAreNonnullByDefault;
            |import net.minecraft.FieldsAreNonnullByDefault;
            |import net.minecraft.MethodsReturnNonnullByDefault;
        """.stripMargin().trim()

        packageInfoFile.text = pkgInfoText
      }
    }
  }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll(['-Xmaxerrs', '100000'])
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
        minecraft_version       : minecraft_version,
        minecraft_version_range : minecraft_version_range,
        neo_version             : neo_version,
        neo_version_range       : neo_version_range,
        loader_version_range    : loader_version_range,
        mod_license             : mod_license,
        mod_version             : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

def lastCommit = providers.exec {
    commandLine 'git', 'rev-parse', 'HEAD'
}.standardOutput.asText.get().trim()

def penultimateTag = () -> {
    providers.exec {
        commandLine 'git', 'describe', '--abbrev=0', '--tags', 'HEAD~'
    }.standardOutput.asText.get().trim()
}

tasks.named('jar', Jar).configure {
    from([sourceSets.api.output, sourceSets.main.output])
    manifest {
        attributes([
            'Specification-Title'       : project.name,
            'Specification-Vendor'      : 'Sm0keySa1m0n, Edivad99',
            'Specification-Version'     : '1',
            'Implementation-Title'      : project.name,
            'Implementation-Version'    : project.version,
            'Implementation-Vendor'     : 'Sm0keySa1m0n, Edivad99',
            'Implementation-Commit'     : lastCommit,
        ])
    }
}

tasks.register('apiJar', Jar) {
    group = 'build'
    from sourceSets.api.output
    archiveClassifier = 'api'
    manifest.from(jar.manifest)
}

assemble.dependsOn(jar, apiJar)

tasks.register('makeChangelog', GitChangelogTask) {
    fromRepo.set(projectDir.absolutePath.toString())
    fromRevision.set(penultimateTag())
    toRevision.set('HEAD')
    file.set(file('CHANGELOG.md'))
    untaggedName.set('Next release')
    templateContent.set(file('changelog.mustache').text)
    ignoreCommitsIfMessageMatches.set('^.*Merge branch.*$')
}

publishMods {
    displayName = "railcraft-reborn-$minecraft_version-$mod_version"
    version = mod_version
    type = STABLE

    def changelogFile = file('CHANGELOG.md')
    changelog = changelogFile.exists() ? changelogFile.text : 'CHANGELOG.md not found'

    modLoaders.add('neoforge')
    file = jar.archiveFile
    additionalFiles.from(apiJar)

    curseforge {
        projectId = '901491'
        accessToken = providers.environmentVariable('CURSEFORGE_TOKEN')
        minecraftVersions.add(minecraft_version)
    }
    modrinth {
        projectId = 'rO6kKst6'
        accessToken = providers.environmentVariable('MODRINTH_TOKEN')
        minecraftVersions.add(minecraft_version)
    }
}
