# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.3
minecraft_version_range=[1.21.3,1.22)
neo_version=21.3.60
neo_version_range=[21.1.50,)
loader_version_range=[4,)
mod_dev_gradle=2.0.76

## Parchment
parchment_minecraft_version=1.21.3
parchment_mappings_version=2024.12.07

## Mod Properties
mod_version=1.2.3
mod_license=https://github.com/railcraft-reborn/railcraft/blob/1.21.x/LICENSE.md

# Dependencies
jupiter_version=5.10.2
jei_version=19.8.5.118
emi_version=1.1.12
patchouli_version=1.21-87-NEOFORGE-SNAPSHOT
jade_id=5846076
