# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.228
neo_version_range=[21.1.50,)
loader_version_range=[4,)
mod_dev_gradle=2.0.141

## Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod Properties
mod_version=1.2.11
mod_license=https://github.com/railcraft-reborn/railcraft/blob/1.21.x/LICENSE.md

# Dependencies
jupiter_version=5.10.2
jei_version=19.25.0.322
emi_version=1.1.22
patchouli_version=1.21.1-93-NEOFORGE-SNAPSHOT
jade_id=6853386
dynamiclights_id=6044477
