# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true # -30~ seconds trimmed from gradle --scan opt

## Environment Properties
minecraft_version=1.19.2
minecraft_version_range=[1.19.2]
forge_version=43.5.1
forge_version_range=[43,)
loader_version_range=[43,)

## Possible values: official / parchment
mappings_channel=parchment
mapping_version=2022.08.14-1.19.2

## Mod Properties
mod_version=1.1.11
mod_license=https://github.com/railcraft-reborn/railcraft/blob/1.19.x/LICENSE.md

# Dependencies
mixin_version=0.8.5
jupiter_version=5.10.1
jei_version=11.8.1.1034
emi_version=1.1.4
patchouli_version=1.19.2-77
jade_id_api=4914106
jade_id=4914105
