name: Crowdin Upload

on:
  push:
    paths: [ 'src/generated/resources/assets/railcraft/lang/**' ]
    branches: [ 1.20.x ]
  workflow_dispatch:

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Push
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
